# Generated by Django 4.0.6 on 2023-07-16 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='image10',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='image4',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='image5',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='image6',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='image7',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='image8',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='image9',
            field=models.TextField(),
        ),
    ]
